using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;
using TMPro;

[UdonBehaviourSyncMode(BehaviourSyncMode.Manual)]
public class QuestionScript : UdonSharpBehaviour
{
    [SerializeField, Tooltip("The TextMeshPro component to display the selected text")]
    private TextMeshPro questionDisplayText;
    
    [SerializeField, TextArea(3, 5), Tooltip("Array of random questions")]
    private string[] questions = new string[]
    {
        "Are you afraid of getting older? Why?",
        "Describe the career of your ideal partner.",
        "Describe the most dangerous situation you have ever been in.",
        "Describe your perfect weekend getaway.",
        "Do you want to have a child one day? Why?",
        "Have you ever had your fortune told? How was it?",
        "Head, Heart, Gut - which one do you listen to the most?",
        "How much money would you need to feel financially secure?",
        "How spiritual are you, from 1 to 10?",
        "How would you like to live in old age?",
        "If you could have a superpower, what would it be and why?",
        "If you could have another home anywhere in the world, where would it be?",
        "If you could have dinner with a celebrity or fictional character, who would it be and why?",
        "If you could invite any three people, dead or alive, to a dinner party, who would they be and why?",
        "If you could travel back in time, which historical event would you like to witness?",
        "If you had a time machine, which mistake would you like to return to and fix?",
        "Is there any stranger you met long ago that you still think about to this day?",
        "What advice did you receive as a child that you still follow today?",
        "What are three things you can reach right now without getting up?",
        "What are you looking forward to?",
        "What could you have done with a bit more luck and encouragement?",
        "What do you love and hate most about the world?",
        "What do you spend the most money on?",
        "What do you think about the most when daydreaming",
        "What do you wear when you want to look attractive?",
        "What is a guilty pleasure you enjoy but rarely admit to?",
        "What is a meal that others enjoy eating, and that you are good at cooking?",
        "What is a personal goal you have right now?",
        "What is a quote or mantra you live by?",
        "What is a random act of kindness you have experienced or witnessed?",
        "What is one small thing that makes you smile every day?",
        "What is one thing someone can be sure of when hanging out with you?",
        "What is the best memory you have had inside VRChat?",
        "What is the most embarrassing thing you have ever done?",
        "What is the most interesting or bizarre coincidence ever experienced?",
        "What is the most unusual or unexpected place you've ever visited?",
        "What is the most valuable lesson you've learned from a difficult situation?",
        "What is your favorite comfort food?",
        "What is your favorite family tradition or holiday celebration?",
        "What is your favorite memory with a close friend or family member?",
        "What is your favorite thing about the city or town you live in?",
        "What is your favorite type of weather and why?",
        "What is your favorite way to relax after a long day?",
        "What new skill would you like to learn?",
        "What was the last book or movie that made you cry?",
        "What was your most memorable dream or nightmare?",
        "What was your stupidest financial decision of all time?",
        "What would be the ideal place to go on a date?",
        "What's something you used to believe but have since changed your mind about?",
        "When was the last time you did something for the first time?",
        "When was the last time you said \"I love you?\"",
        "Which of your friends do you envy the most?",
        "Which part of your body do you like the most?",
        "Who are the two people you've been thinking about a lot lately?",
        "Who do you genuinely want the best for?",
        "Who do you go to for advice?",
        "Who is your all-time favorite co-worker, and what do you like about that person?",
        "Who is your youngest and oldest friend?",
        "Is romance something that resonates with you? In what way?",
        "Are you in a relationship? What's the reason behind your relationship status?",
        "In three words, describe the last person who answered a question.",
        "If given the option, would you choose to live forever? Why or why not?",
        "If you could become an expert in any subject, what would it be and why?",
        "Name three people you'd choose for a road trip and the destination you'd pick.",
        "If you could instantly master a new language, which one would you choose and why?",
        "Is there a particular activity you wish you had a friend to do it with?",
        "What is something you are no longer afraid of?",
        "Were you a \"problem child\" growing up? If so, why?",
        "In three words, describe your personality.",
        "What skills or talents do you excel at?",
        "What makes you highly anxious in public?",
        "What activities did you love doing as a child but hate doing now?",
        "When going out to eat/drink, what is your usual order?",
        "What hobby or interest have you not pursued yet but wish to?",
        "Where do you go to recharge your life battery?",
        "When you are feeling down, what music might you listen to?",
        "What significant experience from the last two years changed your life?",
        "What is the best compliment you've ever been given?",
        "What is the most challenging obstacle you've successfully overcome?",
        "What is the  best lesson you've taken away from a mistake in a relationship?",
        "What street in your town do you favor the most, and how would you describe it?",
        "What role do you usually take when working on a team project?",
        "What type of person do you typically attract or find falling for you?",
        "What recent action have you done that made someone genuinely happy?",
        "Which toys were your favorites as a child, and what are your favorite ones now?",
        "When was the last time you comforted someone?",
        "Which decade do you find the most enjoyable, and why?",

        "Are you a morning person or a night owl, and why?",
        "If you could attend any major event in history, what would it be?",
        "If you could be a character in any fictional universe, which one would you choose?",
        "If you could be an expert in any field overnight, what would it be?",
        "If you could design your own dream world, what would it look like?",
        "If you could eliminate one thing from your daily routine, what would it be?",
        "If you could have a conversation with any fictional character, who would it be?",
        "If you could have a conversation with your future self, what would you ask?",
        "If you could have a conversation with your pet, what would you ask?",
        "If you could have any animal as a pet, mythical or real, what would it be?",
        "If you could have any type of food delivered to you right now, what would it be?",
        "If you could invent a new holiday, what would it celebrate?",
        "If you could learn any instrument effortlessly, which one would it be?",
        "If you could live in any fictional world, which one would it be?",
        "If you could switch lives with someone for a day, who would it be and why?",
        "If you could time travel to your own future, what age would you visit and why?",
        "What's the most beautiful natural landscape you've ever seen?",
        "What's the most beautiful place you've ever visited?",
        "What's the most memorable piece of advice you've ever received?",
        "What is your most treasured possession and why?",
        "What's the most unusual talent or skill you've come across in someone else?",
        "What's your favorite outdoor activity or sport?",
        "What's your favorite season and why?",
        "Name something about yourself that you wish others noticed more?",
        "What's your favorite way to spend a lazy day?",
        "What's your favorite way to stay active or fit?",
        "What's your favorite type of music, and why does it resonate with you?",
        "What's your spirit animal and why?",

        "What qualities do you value most in a friend?",
        "Do you worry about your future, or take things as they come?",
        "Do you consider yourself an introvert or extrovert?",
        "How do you prefer to cook your eggs?",
        "If you could be any animal or creature, which one would you be?",
        "What is the best prank you’ve ever pulled on someone?",
        "Who do you feel the safest around?",
        "What are you putting off right now?",
        "You just won $10000. what are you going to do with the money?",
        "How many pillows do you sleep with?",
        "Are you a clean or messy person?",
        "What three items would you take with you on a deserted island?",
        "If you had a warning label, what would yours say?",
        "What’s something that most people don’t know about you?",
        "What’s something you could talk about for 30 minutes with no preparation?",
        "How do you think your closest friends would describe you? Do you agree?",
        "What’s an activity that instantly calms you?",

        "What incredibly common thing have you never done?",
        "What's the longest trip you've been on?",
        "What catchy jingle or bit of advertising has stuck with you?",
        "What natural landmark would you like to see someday?",
        "What takes a lot of time but is totally worth it?",
        "What's your favorite kind of dessert?",
        "What is the farthest you have ever been from where you were born?",
        "What's something inexpensive that holds a lot of sentimental value to you?",
        "What do you get every time you go grocery shopping?",
        "What's your favorite accessory or clothing item?",
        "What is something you are utterly obsessed with at the moment?",
        "What is your computer or phone wallpaper?",
        "What word or saying from the past do you think needs to make a comeback?",
        "If the internet suddenly stopped existing, what would you do with the time you used to spend on it?",
        "If you could have an endless candle that smelled like anything, what fragrance would you want it to be?",
        "If you didn't have to sleep, what would you do with the extra time?",
        "What age do you wish you could permanently be?",
        "When things break, do you prefer to fix them or replace them?",
        "What improved your life quality so much, you wish you did it sooner?",
        "What's the best food for a food fight?",
        "What's the weather like today where you are?",
        "When people come to you for help, what do they usually want help with?",
        "What's the story behind your username?",
        "What kinds of things do you like to cook or are good at cooking?",
        
        "How would society and daily routines change if sleep wasn't necessary?",
        "Where or what is your happy place?",
        "What would happen if everyone could remember their dreams in vivid detail?",
        "If you had to choose an era to live in for a year, which would it be and why?",
        "What does your idea of a perfect day look like?",
        "If you could decide the theme for the next decade, what would it be and why?",
        "What is your favorite accessory/jewelry piece that you own?",
        "Would you rather lounge by the pool or on the beach?",
        "What is/was your favorite stuffed animal like? Tell us all about them.",
        "What things or people make you the happiest?",
        "What do you think is the most amazing thing about the universe?",
        "What are some little known relationship GREEN flags?",
        "What book or movie profoundly changed your perspective on life? What impact did it have on you?",
        "What was the best vacation you've ever been on?",
        "What is very hard to get and very easy to lose?",
        "What are your favourite activities to do with others?",
        "What time of day do you work best?",

        "What does 'beauty' mean to you?",
        "When was the last time you cried with laughter?",
        "What is your relationship with technology?",
        "Do you have any hidden talents?",
        "On a scale of 1 to 10, how unlucky are you?",
        "How many friend groups do you have?",
        "On a scale from 1 to 10, how often do you lie?",
        "Who do you admire in your friend group?",
        "Do you prefer sunrises OR sunsets? Why?",
        "What is something you can talk about for an hour without preparation?",
        "What are three really small victories you had in the last few days that you're proud of?",
        "How many pillows do you sleep with?",
        "How do you feel about putting pineapple on pizza?",
        "Have you ever visited the dark web?",
        "Do you feel more like a leader or a follower?",
        "What is your greatest strength?",
        "What are your top three long-term goals?",
        "What makes you feel accomplished?",
        "On a scale from 1 to 10, how social are you?",
        "How do you respond in an emergency?",
        "On a scale from 1 to 10, how often do you drink water?",
        "What is your favorite school subject?",
        "Have you ever purchased a house?",
        "How imaginative are you?",
        "What makes you feel safe?",
        "How did you meet your best friend?",
        "If the average human lifespan was 40 years, how would you live your life differently?",
        "Which website should come back from the dead?",
        "On a scale of 1 to 10, how tough are you?",
        "What is your all-time favorite way to sleep?",
        "Describe your perfect day.",
        "Do you like hugs, or do you avoid them?",
        "Are you happy?",
        "What is your favorite orange item?",
        "Are you dyslexic?",
        "Are you ambidextrous, right- or left-handed?",
        "Are you an angel or a demon in disguise? ",
        "What caused you to feel nostalgic recently?",
        "Have you ever been on TV?",
        "Are you more of an explorer or a homebody?",
        "In your friend group, who gets in the most trouble?",
        "If you could delete one website, which one would it be?",
        "If you had a pet parrot, what would you teach it to say?",
        "Would you rather tame a dragon or a dinosaur?",
        "If your friends were food, who would be what?",
        "Do you know a lot about geography? Where is Woolloomooloo?",
        "What can people learn from animals?",
        "What tickles your curiosity?",
        "Out of all of your friends, who do you have an unbreakable bond with?",
        "Do you enjoy trying out new foods? What was the most recent new food you tried?",
        "Name an ice cream flavor that represents your personality.",
        "When you answer the phone, what do you say?",
        "What animal makes your heart melt the moment you see it?",
        "What website should everyone check out?",
        "On a scale from 1 to 10, how good at cooking are you?",
        "Do you know any riddles? If so, share one.",
        "Do you have a running joke in your friend group?",
        "Is the glass half empty or half full?",
        "On a scale from 1 to 10, how good are you at saving money?",
        "If you could eat in VR, what would you try first?",
        "How ticklish are you?",
        "Do you experience a phantom sense in VR?",
        "What do you daydream about?",
        "Name your home world and why is it your home world?",
        "Are you more into one's looks or brains?",
        "If you were an action figure, what accessories would you be sold with?",
        "What is your favorite thing about Europe?",
        "How many hats do you own?",
        "When you are upset, ill, or enraged, how do you prefer to be comforted?",
        "What was your first video game console?",
        "How would you like to be remembered by a stranger?",
        "If you could live in any alternate universe, where would you go?",
        "What is the weirdest fact you know?",
        "If you could tell your younger self anything, what would it be?",
        "What is your biggest secret indulgence?",
        "What are three things you are thankful for?",
        "When you see a puddle on the ground, do you walk around it, or jump in it?",

        "Do you prefer playing games alone, with friends, or with strangers?",
        "What is the weirdest food or food combination that you've eaten?",
        "If you had intro/theme music, what song would it be?",
        "Whose a YouTuber that you watched when you were younger but grew out of watching?",
        "What game would you like to get a sequel?",
        "What is an online game that was discontinued or shut down you'd want to come back?",
        "What was your first video gaming platform and what was your game of choice?",
        "What is your favorite dinosaur and why?",
        "What is the cheesiest pickup line you used on someone personally?",
        "What is something you did today?",
        "What is something you are STILL salty about?",
        "What's one thing you're looking forward to today?",
        "What about you now would most impress your younger self?",
        "Do you have any pets? If not, do you want any?",
        "Do you have any tattoos? If not, do you want any?",
        "What is the most interesting thing you see on your way to school or work?",
        "What would society look like if everyone could teleport anywhere at will?",
        "What is your ideal snack item of choice?",
        "What is your favorite type of stuffed animal (texture, animal, brand, etc.)?",
        "If you could place any object on another planet, purely to confuse NASA scientists, what would it be?",
        "Whats your favorite dragon from media?",

        "What was your earliest favorite movie and why?",
        "What class did you enjoy the most in school or college?",
        "If you had a million dollars, what would you do?",
        "What is a quote or popular reference you mention often?",
        "What would you say to someone who feels anxious right now?",
        "What would you say to someone who looks up to you and why?",
        "Do you have a hobby that few people get to see? If so, why?",
        "What was your earliest memory using a computer?",
        "What was the first video game you ever played?",
        "What would be the first thing you do tomorrow if you woke up as your current VRChat avatar?",
        "What would life be like if every VRChat user woke up tomorrow as their VRChat avatar?",
        "Do you ever dream about dragons? What do they look like?",
        "How would you describe \"real life\" to someone in your dreams?",
        "What question do you want someone to ask you right now?",
        "What would you plant in your ideal garden?",
        "List three important things that video games taught you.",
        "If your mind was a house, what would it look like?",
        "What \"social norms\" would you erase and why?",
        "Do you cook? Why or why not?",
        "What is one meal you are decently good at cooking?",
        "What was the last meal you cooked for yourself?",
        "What did you eat today?",
        "What is a habit you have but wish you didn't?",
        "What do you do for fun?",
        "What makes you laugh every time?",
        "What are three things you are curious about?",
        "what are three things you are passionate about?",
        "What kind of dreams do you enjoy the most?",
        "What is something you do that others may find annoying?",
        "What is your superpower?",
        "How did you first discover the fandom you are in?",
        "Whats a power you didn't ask for but is cool/useful sometimes?",
        "What is your favorite comic/webcomic and why?",
        "Are you a spontaneous person or do you plan your days thoughtfully?",
        "When was the last time you felt anxious and how did you overcome it?",
        "What topics are you most comfortable talking about?",
        "How do you like to get cozy?",
        "List three YouTubers you watch.",
        "This is not a question. Remember to stay hydrated! :>",
        "What makes a friend a BEST FRIEND?",
        "What is your earliest memory?",
        "What was the most recent thing you built?",
        "Do you enjoy cold or warm environments?",
        "List three things that are nostalgic to you.",
        "How do you learn a new skill?",
        "How do you typically approach a difficult topic or situation?",
        "What is something you wish more people understood about you?",
        "How would you describe the first half of your life?",
        "What were you up to half-your-life ago?",
        "What motivates you?",
        "What aspect of yourself are you most critical about?",
        "Do you know anyone in-person who is also part of your fandom or shares your same interests?",
        "What do you never cheap-out on?",
        "What purchase is worth every penny?",
        "What was the last thing you fixed?",
        "What drains you of energy? What fills you with energy?",
        "What tool do you think everyone needs?",
        "What game most defines you today?",
        "Describe the weather outside right now.",
        "How do you meet new friends?",
        "Do you ever give random complements to strangers? Why or why not?",
        "What advice do you have for someone that wants to make more friends?",
        "What advice do you have for someone that looks up to you?",
        "What is your favorite game genre?",
        "How do you introduce yourself to someone new?",
        "How do you introduce a new friend to your other friends?",
        "You are given a magic dragon. What are your three wishes?",
        "What is something that bothers you but you can't change?",
        "What else are you doing tonight?",
        "Are you more of an empathetic or sympathetic person?",
        "What animal or creature best defines you and why?",
        "What fear do you have that holds you back?",
        "Do you always think about what other people think about you?",
        "What are you a born natural at?",
        "Do you keep a Journal?",
        "What is something you told yourself you'd do tomorrow?",
        "When given a task or assignment, do you do it ASAP or wait until the last minute?",
        "If your best friend disappeared for a week, would you be alarmed?",
        "How are you?",
        "What do you want more of?",
        "What was the last thing you drew/sketched?",
        "When was the last time you vibed with someone?",
        "When looking for a partner, are you more romantically attracted, intimately attracted, both, or neither?",
        "Do you love learning new things?",
        "What is something you wanted to say earlier, but never got the chance to?",
        "What is something about yourself that you are proud of?",
        "Do you live in the moment or dwell in the past?",
        "Whats on your mind right now?",
        "What do you dedicate the most time toward?",
        "What would you be if not a human?",
        "What color is your room?",
        "What did you want to be as a kid? what are you now?",
        "Do you ever play devils advocate with someone you otherwise agree with?",
        "Which one of your friends have you known the longest? How did you first meet?",
        "If you were a dragon, what would you look like?",
        "If you could go anywhere in the world, where would you go?",
        "If traveling across the world was as simple as a hop, skip, and jump, where would you go?",
        "If you woke up as your main OC or avatar IRL tomorrow, who would be the first person you tell?",
        "If you had wings, but couldn't fly, what else would you use your wings for?",
        "If you could invite anyone over right now, who would it be?",
        "\"Wake up, you're dreaming.\" Where would you wake up?",
        "What was the last thing you debated getting, but talked yourself out of?",
        "What was the last risk you took?",
        "What is your favorite food to cook?",
        "What do you like about yourself?",
        "What do you like about the person closest to you?",
        "After you meet someone for the first time, what things do you tend to remember about them?",
        "Do you have a 3D printer? What was the last thing you printed on it?",
        "What is something you wish you can change about yourself?",
        "What do you think life was like in the year that you were born?",
        "What was your dream job as a child?",
        "Do you have any pet peeves?",
        "What is on your mind right now?",
        "What is your favorite kind of store?",
        "Where were you half your life ago?",
        "What book have you read that stuck with you?",
        "What is something you wish to do more of?",
        "What is something or some place you like to explore?",
        "Whats the last piece of music you listened to?",
        "What kind of games do you like to play?",
        "What is something you worked hard on but not many people noticed?",
        "What did you do today?",
        "What meme is on your mind right now?",
        "List three things you can hear right now.",
        "What is something you take for granted?",
        "What is your \"million dollar idea?\"",
        "Who was your most favorite teacher in school?",
        "What was one of your old nicknames?",
        "What is a strange food combination you enjoy?",
        "What strange food combination do you not understand?",
        "What are three oddities about yourself?",
        "What things make you feel uncomfortable?",
        "What’s your zodiac sign, and does it resonate with you?",
        "How would you improve your current living space right now, if you could?",
        "What is a hobby would you like to pick up?",
        "What do you collect/hoard?",
        "What is something you are thankful for?",
        "What is something you need more of in your life right now?",
        "If you could change one thing about the world, what would it be?",
        "How do YOU pronounce \"Oatmeal?\"",

        "What kind of videos do you like to watch",
        "What made you choose your username and why?",
        "What is something about your body that you take for granted?",
        "Do you believe in hate? Why?",
        "What is a TV show you used to love watching, but no longer airs? ",
        "What hobbies do you have?",
        "What is something you have recently grown tolerant of?",
        "Can you do any funny voices?",
        "What is your favorite VRChat group that you are in?",
        "What is something you wish your friend groups did more of?",
        "Have you ever had a vivid dream you couldn't possibly explain?",
        "Do you ever have reoccurring dreams?",
        "What is your favorite US State?",
        "What is your favorite European country?",
        "How would you describe your mood right now?",
        "What was your first experience like in a library?",
        "Are you good at teaching people? If so, what would you teach?",
        "In your friend group, who is most likely to save you?",
        "What do you think your family was up to in the 1800s?",
        "Do you consider yourself stoic?",
        "Do you curse a lot? Why?",
        "What would be the most delicious food and drink spread you could eat right now?",
        "Do you prefer white, milk or dark chocolate?",
        "Are you good at acting?",
        "What could you go on about for hours?",
        "Why do you think animals dream?",
        "What is the most trouble you got in while time traveling?",

        "Did you hug your best friend today?",
        "When do you know it's time for a PC upgrade?",
        "Can you dance?",

        "How does you in VRChat differ from you in real life? How are they similar?",
        "What would the world be like if everyone had access to a character editor screen?",
        "What would you do if your VRChat avatar spawned in beside you one morning IRL?",
        "How do you communicate without words?",
        "What does your mind's voice sound like?",
        "If you woke up as your ideal self tomorrow, what would change?",
        "What was the last thing you focused on?",
        "What makes you smile?",
        "How do you make others smile?",
        "Can you make someone smile on command?",
        "Do you ever daydream about other worlds?",
        "What do you think is more important, Physics or Philosophy?",
        "What kind of car do you drive? (if any)",
        "Why did you get into VRChat?",
        "What aspect about you do you think would surprise most others?",
        "What kind of potato is best?",
        "How do you deal with something you don't understand?",
        "Do you play any instruments?",
        "What was the last thing you took a photo of?",
        "What kind of food can you like unregrettably eat forever?",
        "Describe your most recent dream.",
        "Do you meditate? If so, what is your method?",
        "How did you first get into your main hobby or passion?",
        "What is something important to you that is very hard to communicate.",
        "What would life be like if sleep was not required?",
        "Describe the last experience of deja vu you had.",
        "What does regret mean to you?",
        "What was the last piece of music you remember listening to?",
        "What rare/special item would you drop if you were a character in a video game?",
        "What gift can someone give you to increase your friendship level?",
        "What is a subject that makes you excited?",
        "What are your preferred pizza styles and toppings?"
    };
    
    [UdonSynced]
    private string currentDisplayText = "";
    
    void Start()
    {
        if (questionDisplayText == null)
        {
            Debug.LogError("[QuestionScript] Question Display Text reference is missing!");
        }
    }
    
    public override void Interact()
    {
        DisplayRandomQuestion();
    }
    
    public void OnDeserialization()
    {
        // Update display text when network data is received
        if (questionDisplayText != null)
        {
            questionDisplayText.text = currentDisplayText;
        }
    }
    
    public void DisplayRandomQuestion()
    {
        // Only the owner should change the values
        if (Networking.IsOwner(gameObject))
        {
            if (questions.Length > 0)
            {
                int randomIndex = Random.Range(0, questions.Length);
                currentDisplayText = questions[randomIndex];
                
                // Update the text locally
                if (questionDisplayText != null)
                {
                    questionDisplayText.text = currentDisplayText;
                }
                
                // Request serialization to sync with all clients
                RequestSerialization();
            }
        }
        else
        {
            // If we're not the owner, request ownership before changing values
            Networking.SetOwner(Networking.LocalPlayer, gameObject);
            SendCustomEventDelayedFrames(nameof(DisplayRandomQuestion), 1);
        }
    }
}
