using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;
using TMPro;

[UdonBehaviourSyncMode(BehaviourSyncMode.Manual)]
public class TruthScript : UdonSharpBehaviour
{
    [SerializeField, Tooltip("The TextMeshPro component to display the selected text")]
    private TextMeshPro questionDisplayText;
    
    [SerializeField, TextArea(3, 5), Tooltip("Array of truth questions")]
    private string[] truthQuestions = new string[]
    {
        "Did you ever drink before you were of the legal drinking age?",
        "What is the craziest thing you have done while under the influence?",
        "What was the last thing you searched for on your phone web browser?",
        "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
        "Have you ever walked in on your parents doing it?",
        "After you’ve dropped a piece of food, what’s the longest time you’ve left it on the ground and then ate it?",
        "Have you ever tasted a booger?",
        "What’s the first thing you would do if you woke up one day as the opposite sex?",
        "If someone heard you snoring, would they say it’s obnoxiously loud?",
        "Have you ever peed in a pool full of people?",
        "Who do you think is the worst dressed person in this room?",
        "Have you ever farted in an elevator?",
        "True or false? You have a crush on an elderly person?",
        "What is the largest amount of food you’ve eaten in one sitting?",
        "Of the people in this room, who do you want to trade lives with for one day?",
        "What are some things you think about when sitting on the toilet?",
        "What is the most embarrassing situation you’ve ever been a part of?",
        "Did you have an imaginary friend growing up?",
        "Do you cover your eyes during a scary part in a movie?",
        "Have you ever practiced kissing in a mirror?",
        "What, if any, sport do you absolutely hate against popular opinion?",
        "Did your parents ever give you the “birds and the bees” talk?",
        "What is your guilty pleasure that you never tell anyone?",
        "What is your worst or most embarrassing habit?",
        "Has anyone ever walked in on you when taking a dump in the bathroom?",
        "Have you ever had a major wardrobe malfunction while in public?",
        "Have you ever accidentally walked into a wall or building?",
        "Do you pick your nose when you’re alone?",
        "How much older of an individual would you enter a relationship with?",
        "Do you pee in the shower?",
        "Have you ever peed yourself at school before?",
        "What was your most embarrassing moment in public?",
        "Have you ever farted loudly in class or another social setting?",
        "Do you ever talk to yourself in the mirror?",
        "What is your guilty pleasure?",
        "You’re in a public restroom and just pooped, then you realized your stall has no toilet paper. What do you do?",
        "What would be in your web history that you’d be embarrassed if someone saw?",
        "Have you ever tried to take a sexy or naked picture of yourself?",
        "Do you sleep with a stuffed animal or something else for comfort?",
        "Do you drool in your sleep?",
        "Do you talk in your sleep?",
        "Who are you secretly attracted to?",
        "Do you think kittens are cute?",
        "Who do you like the least in this room and why?",
        "What does your dream boy or girl look like?",
        "What is your go-to song for the shower?",
        "Who is the sexiest person in this room?",
        "How would you rate your looks on a scale of 1 to 10?",
        "Would you rather have sex with [insert name] in secret or not have sex with that person but everyone thinks you did?",
        "What things do you not like about me?",
        "What color and kind of underwear are you wearing right now?",
        "What song do you enjoy in privacy?",
        "What was the last thing you texted someone of the opposite sex?",
        "If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?",
        "Have you ever accidentally revealed a friends secret?",
        "Do you think that you and your current girlfriend or boyfriend will ever be married?",
        "How often do you wash your undergarments?",
        "Have you ever tasted ear wax?",
        "Have you ever farted and then blamed someone else?",
        "Have you ever tasted your sweat?",
        "What is the most illegal thing you’ve ever done?",
        "Who is your favorite person in you immediate family?",
        "Would you trade your sibling in for a million dollars if there were no other consequences?",
        "Would you trade in your dog for a million dollars?",
        "What is your biggest pet peeve that other people do?",
        "If you were to join the military what job do you think you’d enjoy the most ?",
        "If you were allowed to marry more than one person, would you? Who would you choose to marry?",
        "Would you rather lose your sex organs forever or gain 200 pounds only in your stomach?",
        "Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?",
        "If you could only hear one song for the rest of your life, what would it be?",
        "If you lost one day of your life every time you said a swear word, would you try not to do it?",
        "Who in this room would be the worst person to date? Why?",
        "Would you rather live with no internet or no A/C or heating?",
        "What was your favorite childhood video game?",
        "If someone offered you $1 million dollars to break up with your girlfriend/boyfriend, would you do it?",
        "If you were reborn, what decade would you want to be born in?",
        "If you could go back in time in erase one thing you said or did, what would it be?",
        "Has your boyfriend or girlfriend ever embarrassed you?",
        "Have you ever thought about cheating on your partner?",
        "If you could suddenly become invisible, what would you do?",
        "Have you ever been caught checking someone out?",
        "What is your favorite alcoholic beverage?",
        "Have you ever waved at someone thinking they saw you when really they didn’t? What did you do when you realized it?",
        "What’s the longest time you’ve stayed in the bathroom, and why did you stay for that long?",
        "What’s the most unflattering school picture of you?",
        "Have you ever cried because you missed your parents so much?",
        "Do you prefer a bath or a shower? Why?",
        "Would you rather be caught picking your nose or picking a wedgie?",
        "Describe the strangest dream you’ve ever had. Did you like it?",
        "Have you ever posted something on social media that you regret?",
        "What is your biggest and most irrational fear?",
        "What is the scariest movie you have ever seen?",
        "Do you sing in the shower?",
        "Have you ever ding dong ditched someone?",
        "What is something you have done that has made you really proud?",
        "The world ends next week and you can do anything you want (even if it’s illegal). What would you do?",
        "Would you wear your shirt inside out for a whole day if someone paid you $100?",
        "What salad dressing could you drink out of the bottle?",
        "What is the most childish thing that you still do?",
        "How far would you go to land the guy or girl of your dreams?",
        "If you had to choose would you rather have a broken arm or a broken leg and why?",
        "Tell us about a time you embarrassed yourself in front of a crush.",
        "Have you ever kept a library book?",
        "Who is one person you pretend to like, but actually don’t?",
        "What children’s movie could you watch over and over again?",
        "Do you have bad foot odor?",
        "Do you have any silly nicknames?",
        "When was the last time you wet the bed?",
        "How many pancakes have you eaten in a single sitting?",
        "Have you ever accidentally hit something with your car?",
        "If you had to make out with any Disney character, who would it be?",
        "Have you ever watched a movie you knew you shouldn’t?",
        "Have you ever wanted to try LARP (Live Action Role-Play)?",
        "What app on your phone do you waste the most time on?",
        "Have you ever pretended to be sick to get out of something? If so, what was it?",
        "What is the most food you’ve eaten in a single sitting?",
        "What is the single most painful experience of your life?",
        "Do you dance when you’re by yourself?",
        "Would you have voted for or against Trump?",
        "What song on the radio do you sing with every time it comes on?",
        "Do you sleep with a stuffed animal?",
        "Do you own a pair of footie pajamas?",
        "What is the meanest thing you’ve ever said to someone?",
        "Are you scared of the dark?",
        "What ‘As seen on TV’ product do you secretly want to buy?",
        "Do you still take bubble baths?",
        "If you were home by yourself all day, what would you do?",
        "How many selfies do you take a day?",
        "Would you date your high school crush today?",
        "What is something you’ve done to try to be ‘cooler’?",
        "When was the last time you brushed your teeth?",
        "How often do you wear the same outfit in a week?",
        "Have you ever used self tanner?",
        "What is your favorite breed of dog?",
        "What do your favorite pajamas look like?",
        "Do you have a security blanket?",
        "Do you still have something you have cherished from childhood?",
        "Have you ever eaten something off the floor?",
        "Have you ever butt-dialed someone?",
        "Do you like hanging out with your parents?",
        "Do you prefer staying up late or going to bed early?",
        "Have you ever got caught doing something you shouldn’t?",
        "What part of your body do you love and which part do you hate?",
        "Have you ever had lice?",
        "Have you ever pooped your pants?",
        "What was the last rate-R movie you watched?",
        "What is your favorite type of ice cream?",
        "Do you lick your plate?",
        "What is something that no one else knows about you?",
        "Have you ever stolen anything?",
        "What is the most embarrassing thing you've ever done?",
        "What is the most embarrassing thing you've ever said?",
        "What is the most embarrassing thing you've ever seen?",
        "What is the most embarrassing thing you've ever heard?",
        "What is the most embarrassing thing you've ever smelled?",
        "What is the most embarrassing thing you've ever tasted?",
        "What is the most embarrassing thing you've ever touched?",
        "Have you ever had a crush on one of your teachers?",
        "Have you ever cheated on a test?",
        "Have you ever cheated on a partner?",
        "Who was your first celebrity crush?",
        "Do you believe in any superstitions?",
        "Do you believe in any conspiracy theories?",
        "Have you showered today?",
        "Where's the farthest you've traveled?", 
        "What's the weirdest food combo that you eat?",
        "What's the meanest thing you have ever said to someone?",
        "What was the last movie that made you cry?",
        "If you had to be stuck on a desert island with any celebrity, who would it be?",
        "Have you ever gotten arrested or almost gotten arrested?",
        "What would your stripper name be?",
        "Have you ever blamed a fart on somebody else?",
        "When is the last time you peed in your pants?",
        "Would you volunteer as tribute for anyone in the Hunger Games?",
        "Who is your least favorite person in the room?",
        "If you were famous, what would it be for?",
        "What is your biggest insecurity?",
        "Have you ever eaten your own boogers?",
        "What is the meanest practical joke you have ever pulled on someone?",
        "Who was the last person you betrayed?",
        "What is the last thing you searched for on your phone?",
        "What's the stupidest thing you were scared of as a kid?",
        "Do you sing in the shower?",
        "Do you cheat at board games?",
        "What is your least favorite feature?",
        "Have you ever sung karaoke?",
        "Who is your least favorite family member?",
        "Have you ever lied on your resume?",
        "Do you ever intentionally smell your own farts?",
        "Have you ever pretended to not get a text to get out of doing something?",
        "What is the worst thing you have ever smelled?",
        "Have you ever pretend to cry to get out of a speeding ticket?",
        "What is the craziest dream you can remember having?",
        "What is an instant deal breaker in a new relationship?",
        "Have you ever performed in front of a crowd?",
        "What is your biggest regret in life?",
        "Do you have any hidden talents?",
        "Have you ever been in a fight?",
        "Do you walk around naked when you are home alone?",
        "What is the worst date you've ever been on?",
        "Do you believe in love at first sight?",
        "What is the dumbest thing you have done while drunk?",
        "What's the most inappropriate time you have ever laughed?",
        "Have you ever won an award you didn't deserve?",
        "Have you ever shoplifted?",
        "What is the worst place you have ever thrown up?",
        "What is your worst habit?",
        "What would your dream job be?",
        "Are there any movies that are widely accepted as bad, but you love? If so which ones?",
        "Would you ever date someone much older than you?",
        "Have you ever eaten food that's been on the floor longer than 5 seconds?",
        "What is your favorite possession?",
        "What is the dumbest thing you have ever lied about?",
        "What is the worst thing you have ever tasted?",
        "What is the worst type of music?",
        "Which celebrity do you hate the most?",
        "Have you ever intentionally sabotaged a coworker?",
        "What do you think happens when you die?",
        "What is your biggest guilty pleasure song/artist?",
        "Which is worse, physical pain or emotional pain?",
        "Who is the biggest flirt in the room?",
        "Would you ever get plastic surgery?",
        "What is your least favorite sport to play?",
        "Who was the last person you said \"I love you\" to?",
        "Where do you want to travel to the most?",
        "Do you still know your first crush?",
        "What word do you hate the most?",
        "What is the worst rumor you've ever started or participated in?",
        "If you could switch bodies with anyone in the world, who would it be?",
        "Would you ever consider being a nudist?",
        "Do you believe in soul mates?",
        "What is the most expensive gift you have ever bought someone?",
        "Have you ever been fired from a job?",
        "Would you rather become an astronaut or movie star?",
        "Who is your hero?",
        "Who did you have your best kiss with?",
        "Has a Pixar movie ever made you cry?",
        "Would you marry someone you didn't love if they were really rich?",
        "Without saying who, do you want to kiss any of the other players?",
        "Are you more likely to be 10 minutes late or 10 minutes early?",
        "Have you ever been on TV?",
        "Do you think you could go a month without using the internet?",
        "What's something you wish you were better at?",
        "Have you ever had a near-death experience?",
        "Do you think cheating is ever justified?",
        "Have you ever compromised your morals for money?",
        "Do you pee in the shower?",
        "When was the last time you turned your phone completely off?",
        "Has a book ever made you cry?",
        "What do you think would be the worst way to die?",
        "What is the worst movie you have ever seen?",
        "Have you ever started a fire while cooking?",
        "Have you ever seriously injured another person?",
        "What is the worst pain you've ever experienced?",
        "What is the most charitable or heroic thing you have done?",
        "How do you think other people perceive you?",
        "Which player made the worst first impression on you?",
        "What is the nastiest smell that you love?",
        "Have you ever compromised your beliefs for a significant other?",
        "Do you believe in fate?",
        "Would you rather be forgotten when you die, or live forever in infamy?",
        "What animal best represents you?",
        "What is the most scared you have ever been?",
        "If you could tattoo clothes on you and be naked forever, would you?",
        "What is the dumbest trend you have ever gone along with?",
        "Did you have an imaginary friend as a child?",
        "Do you believe in astrology?",
        "Have you ever thrown up on a roller coaster?",
        "What is the longest distance you have ever run?",
        "What do you think is the most important lesson to teach your kids?",
        "What is the best advice you have ever received?",
        "What is the worst hair style you've had?",
        "Do you believe in karma?",
        "Have you ever had a paranormal experience?",
        "Which player do you trust the least?",
        "Have you ever said \"I love you\" and not meant it?",
        "If you could slap another player, who would it be?",
        "What is the worst advice you have ever received?",
        "What misconception do people have about you?",
        "Do you believe there is alien life?",
        "Have you ever gotten blackout drunk?",
        "What was your weirdest habit as a kid?",
        "Who would you help hide a body for?",
        "Have you ever given bad advice on purpose?",
        "Do you tell a friend if they have something in their teeth?",
        "If you could only eat one food for the rest of your life, what would it be?",
        "Have you ever had lice?",
        "Do you like being alone or surrounded by friends?",
        "Would you rather have 4 kids or no kids?",
        "Are you a sore loser?",
        "Do you look at your poop before you flush the toilet?",
        "What is more important to you, revenge or forgiveness?",
        "Have you ever gone skinny dipping?",
        "Which player do you trust the most?",
        "Do you believe in ghosts?",
        "What are you most proud of in life?",
        "What is your least favorite memory from high school?",
        "What song can you not help but dance to?",
        "Have you ever smoked marijuana?",
        "What is the pettiest thing you have ever done?",
        "When was the last time you stalked an ex on social media?",
        "What is your biggest pet peeve?",
        "What is a useless skill that you would like to learn?",
        "What is one job that you could never do?",
        "Have you ever had an embarrassing dream about one of the other players?",
        "If you could be a fly on the wall, where would you fly?",
        "What is the worst injury you've ever had?",
        "If you could only eat one candy for the rest of your life, what would it be?",
        "When was the last time you picked your nose?",
        "Are you scared of getting old?",
        "Who has the best butt in the room?",
        "What is something you feel guilty about?",
        "What is the sexiest thing someone can do?",
        "Do you have a crush on any of your coworkers?",
        "Do you still love any of your exes?",
        "Have you ever ghosted somebody?",
        "Have you ever had a one night stand?",
        "What is the scariest thing you've ever done?",
        "Would you eat human meat grown in a lab?",
        "What was your nickname as a child?",
        "What is the worst present anyone has given you?"
    };
    
    [UdonSynced]
    private string currentDisplayText = "";
    
    void Start()
    {
        if (questionDisplayText == null)
        {
            Debug.LogError("[TruthScript] Question Display Text reference is missing!");
        }
    }
    
    public override void Interact()
    {
        DisplayRandomTruth();
    }
    
    public void OnDeserialization()
    {
        // Update display text when network data is received
        if (questionDisplayText != null)
        {
            questionDisplayText.text = currentDisplayText;
        }
    }
    
    public void DisplayRandomTruth()
    {
        // Only the owner should change the values
        if (Networking.IsOwner(gameObject))
        {
            if (truthQuestions.Length > 0)
            {
                int randomIndex = Random.Range(0, truthQuestions.Length);
                currentDisplayText = truthQuestions[randomIndex];
                
                // Update the text locally
                if (questionDisplayText != null)
                {
                    questionDisplayText.text = currentDisplayText;
                }
                
                // Request serialization to sync with all clients
                RequestSerialization();
            }
        }
        else
        {
            // If we're not the owner, request ownership before changing values
            Networking.SetOwner(Networking.LocalPlayer, gameObject);
            SendCustomEventDelayedFrames(nameof(DisplayRandomTruth), 1);
        }
    }
}
